### ISSUE TITLE
the JSON object must be str, bytes or bytearray, not 'NoneType'

### ISSUE THREAD

**Issue by glenosborne** [RidgeRun/gtc-2020-demo#1] opened 2020-05-18 20:56 UTC
when i run the gtc-2020-demo
i get this error
the JSON object must be str, bytes or bytearray, not 'NoneType'

here is the trace
Setting record_h264 pipeline recording/snapshot location to test_record_h264_0.mkv
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 222, in _send_cmd_line
    result = json.loads(jresult)
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pygstc/gstc.py", line 222, in _send_cmd_line
    result = json.loads(jresult)
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
TypeError: the JSON object must be str, bytes or bytearray, not 'NoneType'

jetson TX2
os jetpack 4.4

**Comment by jcaballeros** [comment] 2020-05-18 21:58
Hi glenosborne,

I've seen that error when running the media_server.py without previously starting gstd, please start gstd as in the wiki below:

[Running_The_Demo](https://developer.ridgerun.com/wiki/index.php?title=NVIDIA_GTC_2020:_How_to_build_a_multi-camera_Media_Server_for_AI_processing_on_Jetson#Running_The_Demo)

**Comment by glenosborne** [comment] 2020-05-19 00:51
thanks for the response,

when i run the DISPLAY=:0 gstd -D 
command it does not run in demon mode, that is to say the cursor does not return

it says Gstd version 0.7.0
copyright
log traces will be saved at

then sits there waiting.

i then run 
./media-server.py

in another terminal and it breifly shows two camera outputs to screen then crashes

ERROR: [trt]: coreReadArchive.cpp (38) - serilization Error in verifyHeader: 0 (version tag does not match)

im using tensort 7

any help would be great

regards

**Comment by jcaballeros** [comment] 2020-05-19 17:15
The demo was intended for JP 4.3, however, I tested it with JP 4.4 and it seems to be working well. I checked my environment and it has tensorRT 7.1.

Perhaps there is something missing in your environment. Did you install the board through the sdkmanager?

**Comment by glenosborne** [comment] 2020-05-19 21:55
yes i reflashed my tx2 with nvidia sdk manager,
i selected the deepstream option to be installed with the sdk,

and have followed the install instructions as written
do you need any version information?

ps thanks for the help

**Comment by glenosborne** [comment] 2020-05-20 06:53
contents of log file at 
gstd.log
0:00:45.659653709 ^[[336m21995^[[00m   0x55a61a09e0 ^[[31;01mERROR  ^[[00m ^[[00;01;47m        gstdpipeline gstd_pipeline.c:453:gstd_pipeline_$
0:00:45.660316107 ^[[336m21995^[[00m   0x55a61a09e0 ^[[31;01mERROR  ^[[00m ^[[00;01;47m            gstdlist gstd_list.c:233:gstd_list_create:<$
0:01:39.045465325 ^[[332m 7849^[[00m   0x559a43e5e0 ^[[31;01mERROR  ^[[00m ^[[00;01;47m           gstdstate gstd_state.c:203:gstd_state_update$
0:01:51.832487530 ^[[332m 7849^[[00m   0x559a43e590 ^[[31;01mERROR  ^[[00m ^[[00;01;47m            gstdlist gstd_list.c:367:gstd_list_append_c$
0:01:54.770634216 ^[[332m 7849^[[00m   0x559a43e590 ^[[31;01mERROR  ^[[00m ^[[00;01;47m            gstdlist gstd_list.c:367:gstd_list_append_c$
0:00:08.614064939 ^[[333m 9332^[[00m   0x559e9b65e0 ^[[31;01mERROR  ^[[00m ^[[00;01;47m           gstdstate gstd_state.c:203:gstd_state_update$
0:00:47.470231092 ^[[333m 8840^[[00m   0x55c8ad71e0 ^[[31;01mERROR  ^[[00m ^[[00;01;47m           gstdstate gstd_state.c:203:gstd_state_update$
0:00:04.491042831 ^[[332m24553^[[00m   0x55af77c590 ^[[31;01mERROR  ^[[00m ^[[00;01;47m           gstdstate gstd_state.c:203:gstd_state_update$

**Comment by jcaballeros** [comment] 2020-05-22 15:49
Hi, 

A few ideas:

1. Your GstD version is not the latest, upgrade to  the latest release v0.9.0.

2. Copy the file /opt/nvidia/deepstream/deepstream-5.0/lib/libnvds_mot_klt.so to gtc-2020-demo/deepstream-models/libnvds_mot_klt.so

3. Test that the cameras correspond to the device number that the media server expects and are functional. For that, use the following pipelines to capture and display:

**Devkit camera:**
gst-launch-1.0 nvarguscamerasrc ! nvvidconv ! video/x-raw,format=I420,width=1280,height=720 ! queue ! nveglglessink qos=false async=false sync=false

**USB camera:**
gst-launch-1.0 v4l2src device=/dev/video1 ! video/x-raw,format=YUY2,width=1280,height=720 ! videoconvert ! nveglglessink qos=false async=false sync=false


After this if the media server still doesn't work, I recommend to give it a try with JP 4.3.

**Comment by glenosborne** [comment] 2020-05-23 01:33
thanks for the help,

the first two fixed the problems, 

Your GstD version is not the latest, upgrade to the latest release v0.9.0.

Copy the file /opt/nvidia/deepstream/deepstream-5.0/lib/libnvds_mot_klt.so to gtc-2020-demo/deepstream-models/libnvds_mot_klt.so

the sample works perfectly now and i can explore and hack away at it ,
thank you very much for you help

**Comment by rrcarlosrodriguez** [comment] 2020-05-26 16:28
Hi @glenosborne , I'm glad @jcaballeros helped to fix your issue. Closing this one

**Closed as completed by rrcarlosrodriguez** 2020-05-26 16:28 UTC
